"""add due_date to todos for calendar

Revision ID: 3157b7385dca
Revises: 10dd64f30692
Create Date: 2026-03-10 20:58:47.557206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3157b7385dca'
down_revision = '10dd64f30692'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('due_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_time', postgresql.TIME(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
