"""add due_date to todos for calendar

Revision ID: d411eb49ab79
Revises: 6479ff7be904
Create Date: 2026-03-10 20:38:39.462504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd411eb49ab79'
down_revision = '6479ff7be904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
